KJ_TO_KCAL = 0.239006
REPLACE_INSTRUCTIONS_STRINGS = {
    "Min.": "Min",
    "Ca.": "Ca",
    "ca.": "ca",
    "Sek.": "Sek",
    "Std.": "Std",
    "sek.": "sek",
    "std.": "std",
    "min.": "min",
    "gestr.": "",
    " – ": "-",
    "–": "-",
    "„Hello ": 'Gewürzmischung "',
    "“": '"',
    "„": '"',
    "*": "",
    "gesamte [drei Viertel | gesamte]": "gesamte",
    "ein Viertel [ein Drittel | ein Drittel]": "ein Viertel",
    "Ein Viertel [ein Sechstel | ein Achtel]": "ein Viertel",
    "Guten Appetit!": "",
    "Hälfte ": "HÄLFTE ",
    "ein Drittel ": "EIN DRITTEL ",
    "zwei Drittel ": "ZWEI DRITTEL ",
    "ein Viertel ": "EIN VIERTEL ",
    "drei Viertel ": "DREI VIERTEL ",
}

REPLACE_INSTRUCTION_PATTERNS = {
    r"Hälfte \[.*?\]": "",
    r"halben \[.*?\]": "",
    r"halbe \[.*?\]": "",
    r"(\d)\.(\d)": r"\1.\2",
}

REPLACE_INGREDIENTS_STRINGS = {
    ", Bio": "",
    "Bio ": "",
    "Hello ": "",
    "„": '"',
    "“": '"',
    "frische ": "",
    "frischer ": "",
    "Hartkäse ital. Art, gerieben": "Parmesan",
    "Hartkäse ital. Art, geraspelt": "Parmesan",
    ", gewachst": "",
    ", vegan": "",
    ", natur": "",
    "(Premium)": "",
    "Kochsahne": "Sahne",
    "Gemüsebrühpulver": "Gemüsebrühe",
    "Naturjogurt": "Joghurt",
    "Naturjoghurt": "Joghurt",
    "mittelscharfer Senf": "Senf",
    "rote Chilischote": "Chilischote",
    "Paprika multicolor": "Paprika",
    "rote Spitzpaprika": "Paprika",
    "Basmatireis": "Reis",
    "Jasminreis": "Reis",
    "kleine Salatgurke": "Gurke",
    " in Lake": "",
    ", glatt": "",
    " glatt": "",
    "Weizentortillas": "Tortilla-Wraps",
    "rote Paprika": "Paprika",
    "gelbe Paprika": "Paprika",
    "stückige Tomaten": "Tomaten",
    "rote Kirschtomaten": "Kirschtomate",
    "Rinderhackfleischzubereitung": "Rinderhackfleisch",
    "gemischte Hackfleischzubereitung": "gemischtes Hackfleisch",
    "geriebener Hartkäse": "Parmesan",
    "Libanesisches Fladenbrot": "Fladenbrot",
    " ohne Schale": "",
    "Blütenhonig": "Honig",
    "Hähnchengeschnetzeltes, mariniert": "Hähnchengeschnetzeltes",
    "Bacon (Scheiben)": "Bacon",
    "Buttermilch-Zitronen-Dressing": "Zitronen-Buttermilch",
    "Hartkäse geraspelt": "Parmesan",
    "friche Linguine": "Linguine",
    "Grillkäse Zypriotischer Art": "Grillkäse",
    "Halloumi": "Grillkäse",
    "Quinoa Tri-Color": "Quinoa",
    "Weizenmehl": "Mehl",
    "Tomate (Roma)": "Tomate",
    "Skipjack Thunfisch": "Thunfisch",
    " im eigenen Saft": "",
    "junger Gounda, gerieben": "geriebener Gouda",
    "würziger Gouda, gerieben": "geriebener würziger Gouda",
    "Großgarnelen": "Garnelen",
    "Kirschtomaten (Dose)": "Kirschtomate",
    "lila Karotte": "Karotte",
    "Getrocknete Tomaten mit Kräutern": "Getrocknete Tomaten",
    "Wildpreiselbeeren": "Preiselbeer",
    "und gehobelte Karotten": "& Karotten",
    "veganes cremiges Sojaprodukt": "vegane Sahne",
    "Knoblauch & Zwiebel gehackt in Rapsöl": "Knoblauch & Zwiebel",
    "gehackter Knoblauch & Ingwer in Öl": "Knoblauch & Ingwer",
    "Gehackte Tomaten mit Knoblauch und Zwiebeln": "Tomaten, Knoblauch & Zwiebeln",
    "Marinierter Tofu mit Basilikum": "Marinierter Tofu",
    "Hähncheninnenbrustfilet": "Hähnchenbrustfilet",
    "vegane Brioche Burger Buns": "Burger Buns",
    "Basmati-Wildreis-Mischung": "Basmati-Wildreis",
    "Simmentaler ": "",
    "Hähnchenkeule in Kräutermarinade": "Hähnchenkeule mariniert",
    "Beyond Meat ": "",
    "GREENFORCE ": "",
    "veganer ": "",
    "vegane ": "",
    "veganes ": "",
    "Veganer ": "",
    "Vegane ": "",
    "Veganes ": "",
    "braune Champignons": "Champignons",
    ", ungewachst": "",
    ", vorgeschnitten": "",
    "TABASCO®": "Tabasco",
    "Premium ": "",
    "The Vegetarian Butcher ": "",
    "Fleischtomate": "Tomate",
    "rosa ": "",
    "orange Paprika": "Paprika",
    "Paprika, orange": "Paprika",
    "Kindercurry": "Curry",
    "Bunte Karotten": "Karotten",
    "schwarze Oliven (mit Stein)": "schwarze Oliven",
    "Arborio-Reis": "Risotto-Reis",
    "große Tomate": "Tomate",
    "Rauchsalz": "Salz",
    "Sonnenflocken - Grobes Meersalz": "Salz",
    " von Vivera": "",
    "Polpa Chili": "Chili",
    "Ochsenherztomaten": "Tomate",
    "weiße / braune Bohnen": "weiße Bohnen",
    "gelbe Chilischote": "Chilischote",
    "Schweineschnitzel": "Schnitzel",
    "SalaRico®": "Salat",
    "Tony's Chocolonely ": "",
    "Seelachs ohne Haut": "Seelachs",
    "Champignons in Scheiben": "Champignons",
    "frisches Lorbeerblatt": "Lorbeerblatt",
    "dunkles Ciabatta-Brötchen": "Ciabatta-Brötchen",
    "gelbe Kirschtomaten": "Kirschtomate",
    "Planted ": "",
    "Briochebrötchen mit Sesam": "Briochebrötchen",
    "hartgekochte Eier": "Eier",
    "Eiertomaten": "Tomate",
    "Mehrkornbaguette": "Baguette",
    "rote Frühlingszwiebeln": "Frühlingszwiebeln",
    "Chinakohl, vorgeschnitten": "Chinakohl",
    "roter Rettich": "Rettich",
    "Baby-Mais": "Mais",
    "Blumenkohl-Reis": "Reis",
    "Mildes Sauerkraut": "Sauerkraut",
    "Karotte gelb und orange, geschnitten": "Karotte",
    "Brokkoli-Reis": "Reis",
    "Himbeertomate": "Tomate",
    "gemahlener Zimt": "Zimt",
    "gemahlener Piment": "Piment",
    "Haselnussspätzle": "Spätzle",
    "Bulgur, vorgekocht und gesalzen": "Bulgur",
    "Knoblauch & Zwiebel": "Knoblauchzehe / Zwiebel",
    "Butterbohnen": "grüne Bohnen",
    "Prinzessbohnen": "grüne Bohnen",
    "Hähnchenbrustfilet": "Hähnchenbrust",
    "Hähncheninnenfilets": "Hähnchenbrust",
    "Tortilla-Wraps": "Wraps",
    "Kirschtomaten": "Kirschtomate",
    "veganer Brioche Burger Bun": "Burger Buns",
    "veganer Brioche Bun": "Burger Buns",
    "Brioche Bun": "Burger Buns",
    "saure Sahne": "Sahne",
    "Sahne leicht": "Sahne",
    "vegane Sahne": "Sahne",
    "Schlagsahne": "Sahne",
    "Aprikosenchutney": "Aprikosen-Marmelade",
    "Aprikosenkonfitüre": "Aprikosen-Marmelade",
    "Tomatensugo": "Tomatensauce",
    "Tomatesugo": "Tomatensauce",
    "gemahlener Kumin": "Kreuzkümmel",
    "Sesamsamen": "Sesam",
    "Basmati-Wildreis": "Reis",
    "Hokkaido-Kürbis": "Kürbis",
    "Norwegisches ": "",
    "milder Chili-Mix": "Chili",
    "Chili-Nudeln": "Nudeln",
    "milde Chiliflocken": "Chili",
    "Perlencouscous": "Couscous",
    "Paprika (rot, gelb oder orange)": "Paprika",
    "getrocknete Tomate": "Getrocknete Tomate",
    "Kürbis, geschält und gewürfelt": "Kürbis",
    "Sultaninen": "Rosinen",
    "gerebelter Thymian": "Thymian",
    "grüne Chilischote": "Chilischote",
    "Steinofenbaguette (Inhalt: 250 g)": "Baguette",
    "Parmesan D.O.P.": "Parmesan",
    "Zwiebeln": "Zwiebel",
}
REPLACE_TITLE_STRINGS = {
    ":": "",
    "!": "",
    "&": "und",
}
